### PR TITLE
Revert "Ensure `results` is always an array"

### PR DESCRIPTION
**Pull request by etienne-napoleone**
Reverts tomochain/eth-net-intelligence-api#2

### CODE REVIEW

**Comment by brannondorsey** [comment]
Why was this reverted?

**Comment by etienne-napoleone** [comment]
It introduced another problem and as we switched to the stats directly from the tomochain go client (geth fork), got no time or reason to investigate further.
IIRC, it was hanging after sending the first metrics.

**Comment by brannondorsey** [comment]
I believe that is what I am experiencing as well. Thanks for the info. Do you happen to understand exactly what scenario is causing the crash without the patch?

**Comment by etienne-napoleone** [comment]
I tried this fix based on https://github.com/cubedro/eth-net-intelligence-api/pull/242 .
I checked a bit how it worked at the time but I don't really remember, sorry.

**Comment by brannondorsey** [comment]
No problem, I understand. Thanks for the communication nonetheless.

**Pull request merged**
